let table_data = [
	{
		order_id: '1',
		customer: '2',
		product_name: '3',
		product_per_price: '4',
		product_num: '5',
		product_sum_price: '6',
		order_time: '7',
		cutting_time: '8',
		forg_company_name: '9',
		roughcast_price: '10',
		roughcast_processing_fee: '11',
		material_return_time: '12',
		manager_person_name: '13',
		processing_person_name: '14',
		priduct_processing_fee: '15',
		roughcast_weight: '16',
		product_new_weight: '17',
		iron_filings_weight: '18',
		addition_file_path: '19',
		notes: '20',
	},
	{
		order_id: '1',
		customer: '2',
		product_name: '3',
		product_per_price: '4',
		product_num: '5',
		product_sum_price: '6',
		order_time: '7',
		cutting_time: '8',
		forg_company_name: '9',
		roughcast_price: '10',
		roughcast_processing_fee: '11',
		material_return_time: '12',
		manager_person_name: '13',
		processing_person_name: '14',
		priduct_processing_fee: '15',
		roughcast_weight: '16',
		product_new_weight: '17',
		iron_filings_weight: '18',
		addition_file_path: '19',
		notes: '20',
	},
	{
		order_id: '1',
		customer: '2',
		product_name: '3',
		product_per_price: '4',
		product_num: '5',
		product_sum_price: '6',
		order_time: '7',
		cutting_time: '8',
		forg_company_name: '9',
		roughcast_price: '10',
		roughcast_processing_fee: '11',
		material_return_time: '12',
		manager_person_name: '13',
		processing_person_name: '14',
		priduct_processing_fee: '15',
		roughcast_weight: '16',
		product_new_weight: '17',
		iron_filings_weight: '18',
		addition_file_path: '19',
		notes: '20',
	},
	{
		order_id: '1',
		customer: '2',
		product_name: '3',
		product_per_price: '4',
		product_num: '5',
		product_sum_price: '6',
		order_time: '7',
		cutting_time: '8',
		forg_company_name: '9',
		roughcast_price: '10',
		roughcast_processing_fee: '11',
		material_return_time: '12',
		manager_person_name: '13',
		processing_person_name: '14',
		priduct_processing_fee: '15',
		roughcast_weight: '16',
		product_new_weight: '17',
		iron_filings_weight: '18',
		addition_file_path: '19',
		notes: '20',
	},
	{
		order_id: '1',
		customer: '2',
		product_name: '3',
		product_per_price: '4',
		product_num: '5',
		product_sum_price: '6',
		order_time: '7',
		cutting_time: '8',
		forg_company_name: '9',
		roughcast_price: '10',
		roughcast_processing_fee: '11',
		material_return_time: '12',
		manager_person_name: '13',
		processing_person_name: '14',
		priduct_processing_fee: '15',
		roughcast_weight: '16',
		product_new_weight: '17',
		iron_filings_weight: '18',
		addition_file_path: '19',
		notes: '20',
	},
]

let table_header = {
	id: '数据库编号',
	order_id: '订单编号',
	customer: '成交客户',
	product_name: '成交产品-产品名称',
	product_per_price: '成交产品-销售单价',
	product_num: '成交产品-成交数量',
	product_sum_price: '成交产品-总价',
	order_time: '成交/签约时间',
	cutting_time: '下料时间',
	forg_company_name: '锻打厂家',
	roughcast_price: '毛坯价格',
	roughcast_processing_fee: '毛坯加工费',
	material_return_time: '回料时间',
	manager_person_name: '管理人员',
	processing_person_name: '加工人员',
	priduct_processing_fee: '产品加工费',
	roughcast_weight: '毛坯重量',
	product_new_weight: '产品净重',
	iron_filings_weight: '铁屑重量',
	addition_file_path: '附件',
	notes: '备注',
}
// ['id',
// 'order_id',
// 'customer',
// 'product_name',
// 'product_per_price',
// 'product_num',
// 'product_sum_price',
// 'order_time',
// 'cutting_time',
// 'forg_company_name',
// 'roughcast_price',
// 'roughcast_processing_fee',
// 'material_return_time',
// 'manager_person_name',
// 'processing_person_name',
// 'priduct_processing_fee',
// 'roughcast_weight',
// 'product_new_weight',
// 'iron_filings_weight',
// 'addition_file_path',
// 'notes',]

let info_type = {
	text: 'text',
	time: 'time',
	label: 'label',
	file: 'file',
}

let table_info = {
	id: {
		cant_modify: true,
		type: info_type.label,
	},
	order_id: {
		cant_modify: true,
		type: info_type.label,
	},
	customer: {
		cant_modify: true,
		type: info_type.label,
	},
	product_name: {
		cant_modify: true,
		type: info_type.label,
	},
	product_per_price: {
		cant_modify: true,
		type: info_type.label,
	},
	product_num: {
		cant_modify: true,
		type: info_type.label,
	},
	product_sum_price: {
		cant_modify: true,
		type: info_type.label,
	},
	order_time: {
		cant_modify: true,
		type: info_type.label,
	},
	cutting_time: {
		cant_modify: false,
		type: info_type.time,
	},
	forg_company_name: {
		cant_modify: false,
		type: info_type.text,
	},
	roughcast_price: {
		cant_modify: false,
		type: info_type.text,
	},
	roughcast_processing_fee: {
		cant_modify: false,
		type: info_type.text,
	},
	material_return_time: {
		cant_modify: false,
		type: info_type.time,
	},
	manager_person_name: {
		cant_modify: false,
		type: info_type.text,
	},
	processing_person_name: {
		cant_modify: false,
		type: info_type.text,
	},
	priduct_processing_fee: {
		cant_modify: false,
		type: info_type.text,
	},
	roughcast_weight: {
		cant_modify: true,
		type: info_type.text,
	},
	product_new_weight: {
		cant_modify: true,
		type: info_type.text,
	},
	iron_filings_weight: {
		cant_modify: true,
		type: info_type.text,
	},
	addition_file_path: {
		cant_modify: true,
		type: info_type.text,
	},
	notes: {
		cant_modify: true,
		type: info_type.text,
	},
}

let test = {
	table_data,
	table_header,
	table_info,
	info_type,
}
export default test
